# Generated by Django 6.0.7 on 2026-07-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0002_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=20)),
                ('bus_type', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='', upload_to='bus/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.user')),
            ],
        ),
    ]
