# Generated by Django 6.0.7 on 2026-07-13 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0005_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('journey_date', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='Bus.booking')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bus.bus')),
            ],
            options={
                'unique_together': {('bus', 'seat_number', 'journey_date')},
            },
        ),
    ]
