# Generated by Django 6.0.7 on 2026-07-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0008_booking_payment_id_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_signature',
        ),
    ]
