# Generated by Django 6.0.7 on 2026-07-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0010_booking_payment_id_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(default='booked', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
