# Generated by Django 6.0.7 on 2026-08-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
