# Generated by Django 6.0.7 on 2026-08-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0016_review_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='BusYatra', max_length=100)),
                ('currency', models.CharField(default='INR (₹)', max_length=50)),
                ('welcome_bonus', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('full_refund_hours', models.IntegerField(default=24)),
                ('half_refund_hours', models.IntegerField(default=12)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
