# Generated by Django 6.0.7 on 2026-08-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0017_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
    ]
